### ISSUE TITLE
undefined behavior

### ISSUE THREAD

**Issue by ihsinme** [LindaBoussetila/game_persistence#1]
https://github.com/LindaBoussetila/game_persistence/blob/b502638a552de6c5f47e3ac9f3e4ea015a43c47f/twenty_squares/source/twenty_squares_movement.c#L165

good day.

as far as you can tell from the code in the expression `++i <= INDEX_1_ON_8_COMMON_ROAD ? INDEX_1_ON_8_COMMON_ROAD : i` . the variable is located between the sequence points, so its behavior may not be predictable.

**Comment by LycorisBellua** [comment]
Hi! Thank you for your comment. I don't understand what you mean by sequence points, but when I wrote this code I've done enough tests to be sure the behavior is as I need it to be. I may be wrong of course, we always have surprises haha, but I don't see what I can do to improve it at this point.

However you gave me an idea. It'll be easier for people to understand what works and what doesn't if they have access to the demo and not just the code. Sure they can still clone it but they don't necessarily have the time nor the wish to do that. I'm working on a personal website so I'll be able to put the demo on it, this way they won't need to download anything. As written in the README I don't have time right now as I'm still in a bootcamp, but I'll get to it afterwards.

**Comment by ihsinme** [comment]
good day.
I'm talking about the value of the variable `i`. will not be defined and may be different depending on the compiler.
the simplest fix is `((++i) && i <= INDEX_1_ON_8_COMMON_ROAD ? INDEX_1_ON_8_COMMON_ROAD : i)`.
however, you still need to think about the logic behind the loop. changing iterator in condition initializer, bad practice

**Comment by LycorisBellua** [comment]
I think I see what you mean. It doesn't depend on the compiler as I've defined it myself. Look here and tell me what you think:

`for (i = 0; i < 14; ++i)`
`{`
| .... `if (stone->coordinate == 0 || stone->coordinate == current_player->racetrack[i]->coordinate)`
| .... `{`
| .... | .... `for (i = stone->coordinate == 0 || ++i <= INDEX_1_ON_8_COMMON_ROAD ? INDEX_1_ON_8_COMMON_ROAD : i; i <= INDEX_8_ON_8_COMMON_ROAD; ++i)`
| .... | .... `{`
| .... | .... | .... `if (current_player->racetrack[i]->stone_in_cell != NULL && current_player->racetrack[i]->stone_in_cell->player_id != current_player->id)`
| .... | .... | .... `{`
| .... | .... | .... | .... `coordinate_of_closest_enemy = current_player->racetrack[i]->coordinate;`
| .... | .... | .... | .... `break;`
| .... | .... | .... `}`
| .... | ....  `}`
| .... | ....  `break;`
| .... `}`
`}`

The line you refer to uses "i" from an outer loop, and it is initialized to a value between 0 and 13. Then, if the first if-statement's condition is false, we just browse the loop for nothing. If the condition is true, we enter the inner loop, which indeed updates the value. But what this value becomes doesn't matter anymore because, in the worst case, the last break would get executed so we never return to the outer loop. In the best case, the first break, inside of the inner loop is executed, so we still don't return to the outer loop. I think there is no UB. What do you think?

**Comment by ihsinme** [comment]
you are right about the influence of uncertainty on your further code.

there is uncertainty, but functionally it does not affect your code.

but even with that in mind, I would recommend eliminating the UB in your code. to facilitate further work with the code (support, development)

thanks for your time
